version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install project dependencies
          command: |
            sudo npm install -g yarn
            yarn global add codecov
            yarn global add wait-on
            yarn install --frozen-lockfile

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      
      - run:
          name: Run unit tests
          command: |
            yarn test --coverage
            codecov < ./coverage/lcov.info || true
          

      # - run:
      #   name: deploy  
